"""empty message

Revision ID: cdc591ba1434
Revises: 1cd0ce091901
Create Date: 2021-11-04 12:05:00.516945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cdc591ba1434'
down_revision = '1cd0ce091901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('photos', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('photos', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('photos', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('comments', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
